// In-Memory Data Store Fallback for instant 0-second boot without local MongoDB
const bcrypt = require('bcryptjs');

const initialCategories = [
  { _id: 'cat_1', name: "Women's Fashion", slug: 'womens-fashion', description: 'Trendy dresses, tops, skirts, and statement pieces for every occasion.', icon: 'shirt' },
  { _id: 'cat_2', name: "Men's Fashion", slug: 'mens-fashion', description: 'Sharp streetwear, premium tees, jackets, and modern essentials.', icon: 'user' },
  { _id: 'cat_3', name: 'Shoes & Sneakers', slug: 'shoes-sneakers', description: 'Stylish heels, chunky sneakers, elegant boots, and casual sandals.', icon: 'footprints' },
  { _id: 'cat_4', name: 'Bags & Accessories', slug: 'bags-accessories', description: 'Designer handbags, sleek wallets, trendy sunglasses, and belts.', icon: 'shopping-bag' },
  { _id: 'cat_5', name: 'Beauty & Skincare', slug: 'beauty-skincare', description: 'Luxurious makeup, serums, moisturizers, and signature fragrances.', icon: 'sparkles' },
  { _id: 'cat_6', name: 'Jewelry & Watches', slug: 'jewelry-watches', description: 'Elegant necklaces, rings, bracelets, and precision timepieces.', icon: 'watch' },
  { _id: 'cat_7', name: 'Electronics', slug: 'electronics', description: 'Premium headphones, speakers, tablets, and smart tech gadgets.', icon: 'laptop' },
  { _id: 'cat_8', name: 'Home & Living', slug: 'home-living', description: 'Cozy blankets, decorative pillows, scented candles, and organizers.', icon: 'home' },
  { _id: 'cat_9', name: 'Sports & Fitness', slug: 'sports-fitness', description: 'Yoga mats, gym bags, water bottles, and workout accessories.', icon: 'dumbbell' },
  { _id: 'cat_10', name: 'Kids & Baby', slug: 'kids-baby', description: 'Adorable kids clothing, toys, baby shoes, and cute accessories.', icon: 'baby' },
];

const initialProducts = [
  // ===== WOMEN'S FASHION =====
  {
    _id: 'prod_1',
    name: 'Floral Wrap Midi Dress',
    description: 'Elegant floral wrap midi dress with a flattering V-neckline, ruffle trim, and adjustable waist tie. Made from lightweight chiffon fabric perfect for summer events and casual outings.',
    price: 34.99,
    originalPrice: 59.99,
    categoryName: "Women's Fashion",
    countInStock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.8,
    numReviews: 234,
    soldCount: 1847,
    brand: 'LuxeStyle',
    tags: ['dress', 'floral', 'summer', 'women'],
    colors: ['#E8B4B8', '#2C3E50', '#F5F5DC'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_2',
    name: 'Ribbed Knit Crop Top',
    description: 'Stretchy ribbed knit crop top with a square neckline and short puff sleeves. A versatile wardrobe staple that pairs beautifully with high-waisted jeans or skirts.',
    price: 14.99,
    originalPrice: 24.99,
    categoryName: "Women's Fashion",
    countInStock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.5,
    numReviews: 189,
    soldCount: 3210,
    brand: 'UrbanChic',
    tags: ['top', 'crop', 'casual', 'women'],
    colors: ['#FFFFFF', '#000000', '#FFB6C1', '#87CEEB'],
    sizes: ['XS', 'S', 'M', 'L'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_3',
    name: 'Satin Pleated Midi Skirt',
    description: 'Luxurious satin pleated midi skirt with an elastic high waistband. Features a beautiful sheen and elegant drape for office wear or evening outfits.',
    price: 28.99,
    originalPrice: 45.99,
    categoryName: "Women's Fashion",
    countInStock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.7,
    numReviews: 156,
    soldCount: 2456,
    brand: 'ElegantCo',
    tags: ['skirt', 'satin', 'elegant', 'women'],
    colors: ['#C0C0C0', '#000000', '#8B4513', '#FFD700'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_4',
    name: 'Oversized Blazer Jacket',
    description: 'Structured oversized blazer with notched lapels, padded shoulders, and dual flap pockets. A power piece that elevates any outfit from casual to sophisticated.',
    price: 52.99,
    originalPrice: 79.99,
    categoryName: "Women's Fashion",
    countInStock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.9,
    numReviews: 98,
    soldCount: 987,
    brand: 'NovaTrend',
    tags: ['blazer', 'jacket', 'formal', 'women'],
    colors: ['#000000', '#F5F5DC', '#696969'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_5',
    name: 'High-Waist Wide Leg Pants',
    description: 'Flowy high-waist wide leg pants with a comfortable elastic waistband and side pockets. The perfect balance of comfort and style for everyday wear.',
    price: 26.99,
    originalPrice: 39.99,
    categoryName: "Women's Fashion",
    countInStock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.6,
    numReviews: 145,
    soldCount: 1654,
    brand: 'ComfortFit',
    tags: ['pants', 'wide-leg', 'casual', 'women'],
    colors: ['#000000', '#F5F5DC', '#8B4513'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    createdAt: new Date(),
  },

  // ===== MEN'S FASHION =====
  {
    _id: 'prod_6',
    name: 'Premium Slim Fit Oxford Shirt',
    description: 'Classic Oxford button-down shirt in premium cotton with a tailored slim fit. Features a spread collar, single chest pocket, and mother-of-pearl buttons.',
    price: 38.99,
    originalPrice: 54.99,
    categoryName: "Men's Fashion",
    countInStock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.7,
    numReviews: 203,
    soldCount: 2890,
    brand: 'ClassicMen',
    tags: ['shirt', 'oxford', 'formal', 'men'],
    colors: ['#FFFFFF', '#87CEEB', '#FFC0CB'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_7',
    name: 'Vintage Washed Denim Jacket',
    description: 'Retro-inspired denim jacket with a distressed vintage wash, chest pockets, and adjustable button cuffs. A timeless layer for any season.',
    price: 49.99,
    originalPrice: 69.99,
    categoryName: "Men's Fashion",
    countInStock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.8,
    numReviews: 176,
    soldCount: 1432,
    brand: 'StreetEdge',
    tags: ['jacket', 'denim', 'vintage', 'men'],
    colors: ['#4682B4', '#2F4F4F', '#000000'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_8',
    name: 'Tech Jogger Pants',
    description: 'Modern tech jogger pants with zippered pockets, tapered leg, and moisture-wicking fabric. Perfect for both active and casual everyday wear.',
    price: 32.99,
    originalPrice: 44.99,
    categoryName: "Men's Fashion",
    countInStock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.6,
    numReviews: 221,
    soldCount: 3567,
    brand: 'ActiveWear',
    tags: ['joggers', 'pants', 'casual', 'men'],
    colors: ['#000000', '#808080', '#2F4F4F'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_9',
    name: 'Graphic Print Oversized Tee',
    description: 'Relaxed oversized t-shirt with bold artistic graphic print on premium 100% cotton. Features dropped shoulders and a crew neck for effortless street style.',
    price: 19.99,
    originalPrice: 29.99,
    categoryName: "Men's Fashion",
    countInStock: 150,
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.4,
    numReviews: 312,
    soldCount: 5678,
    brand: 'UrbanPrint',
    tags: ['tshirt', 'graphic', 'streetwear', 'men'],
    colors: ['#FFFFFF', '#000000', '#808080', '#FFD700'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_10',
    name: 'Slim Chino Shorts',
    description: 'Clean-cut slim chino shorts with a flat front and belt loops. Made from breathable twill cotton, ideal for summer days and beach vacations.',
    price: 22.99,
    originalPrice: 34.99,
    categoryName: "Men's Fashion",
    countInStock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.5,
    numReviews: 87,
    soldCount: 1230,
    brand: 'SummerVibe',
    tags: ['shorts', 'chino', 'summer', 'men'],
    colors: ['#F5F5DC', '#2F4F4F', '#000000', '#D2B48C'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },

  // ===== SHOES & SNEAKERS =====
  {
    _id: 'prod_11',
    name: 'Chunky Platform Sneakers',
    description: 'Bold chunky platform sneakers with a 4cm sole lift, breathable mesh upper, and cushioned insole. The ultimate statement shoe for street-style looks.',
    price: 44.99,
    originalPrice: 64.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.7,
    numReviews: 198,
    soldCount: 2345,
    brand: 'StepUp',
    tags: ['sneakers', 'platform', 'chunky', 'unisex'],
    colors: ['#FFFFFF', '#000000', '#FFB6C1'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_12',
    name: 'Pointed Toe Stiletto Heels',
    description: 'Sleek pointed-toe stiletto pumps with an 8cm heel, padded insole, and non-slip sole. A classic power shoe for office and evening events.',
    price: 39.99,
    originalPrice: 59.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.6,
    numReviews: 134,
    soldCount: 1876,
    brand: 'GlamStep',
    tags: ['heels', 'stiletto', 'formal', 'women'],
    colors: ['#000000', '#FF0000', '#F5F5DC'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_13',
    name: 'Retro Running Sneakers',
    description: 'Retro-inspired running sneakers with suede and mesh upper, EVA midsole for cushioning, and rubber outsole for traction. Vintage vibes meet modern comfort.',
    price: 54.99,
    originalPrice: 74.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 42,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: false,
    rating: 4.8,
    numReviews: 267,
    soldCount: 4521,
    brand: 'RetroKicks',
    tags: ['sneakers', 'retro', 'running', 'unisex'],
    colors: ['#FF4500', '#000000', '#FFFFFF', '#4682B4'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_14',
    name: 'Chelsea Leather Boots',
    description: 'Classic Chelsea boots crafted from genuine leather with elastic side panels and a pull tab. Features a durable rubber sole and a sleek, timeless silhouette.',
    price: 68.99,
    originalPrice: 89.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.9,
    numReviews: 89,
    soldCount: 765,
    brand: 'LeatherCraft',
    tags: ['boots', 'chelsea', 'leather', 'unisex'],
    colors: ['#8B4513', '#000000', '#D2B48C'],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_15',
    name: 'Slide Comfort Sandals',
    description: 'Minimalist slide sandals with a contoured cork footbed and soft suede upper. Features arch support and a lightweight EVA outsole for all-day comfort.',
    price: 18.99,
    originalPrice: 28.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 95,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.3,
    numReviews: 342,
    soldCount: 6789,
    brand: 'ComfortWalk',
    tags: ['sandals', 'slides', 'comfort', 'unisex'],
    colors: ['#D2B48C', '#000000', '#808080'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
    createdAt: new Date(),
  },

  // ===== BAGS & ACCESSORIES =====
  {
    _id: 'prod_16',
    name: 'Quilted Chain Shoulder Bag',
    description: 'Elegant quilted shoulder bag with a gold chain strap, magnetic closure, and internal zip pocket. Crafted from premium faux leather for a luxe look.',
    price: 36.99,
    originalPrice: 54.99,
    categoryName: 'Bags & Accessories',
    countInStock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.8,
    numReviews: 167,
    soldCount: 2134,
    brand: 'ChicBags',
    tags: ['bag', 'shoulder', 'quilted', 'women'],
    colors: ['#000000', '#FFFFFF', '#FFB6C1', '#C0C0C0'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_17',
    name: 'Aviator Classic Sunglasses',
    description: 'Iconic aviator sunglasses with UV400 polarized lenses, lightweight metal frame, and adjustable nose pads. A timeless accessory for every face shape.',
    price: 16.99,
    originalPrice: 29.99,
    categoryName: 'Bags & Accessories',
    countInStock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.5,
    numReviews: 456,
    soldCount: 8901,
    brand: 'SunVision',
    tags: ['sunglasses', 'aviator', 'accessories', 'unisex'],
    colors: ['#FFD700', '#C0C0C0', '#000000'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_18',
    name: 'Canvas Tote Bag - Minimalist',
    description: 'Spacious canvas tote bag with reinforced handles, internal pocket, and magnetic snap closure. Perfect for daily commutes, shopping, and beach days.',
    price: 12.99,
    originalPrice: 19.99,
    categoryName: 'Bags & Accessories',
    countInStock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.4,
    numReviews: 278,
    soldCount: 4567,
    brand: 'EcoCarry',
    tags: ['tote', 'canvas', 'bag', 'unisex'],
    colors: ['#F5F5DC', '#000000', '#808080'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_19',
    name: 'Leather Bifold Wallet',
    description: 'Genuine leather bifold wallet with RFID blocking technology, 8 card slots, 2 bill compartments, and an ID window. Slim profile for comfortable pocket carry.',
    price: 24.99,
    originalPrice: 39.99,
    categoryName: 'Bags & Accessories',
    countInStock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: false,
    rating: 4.6,
    numReviews: 123,
    soldCount: 1876,
    brand: 'LeatherCraft',
    tags: ['wallet', 'leather', 'rfid', 'men'],
    colors: ['#8B4513', '#000000', '#D2B48C'],
    sizes: [],
    createdAt: new Date(),
  },

  // ===== BEAUTY & SKINCARE =====
  {
    _id: 'prod_20',
    name: 'Velvet Matte Lipstick Set',
    description: 'Luxurious set of 6 velvet matte lipsticks in curated shades from nude to bold red. Long-lasting formula with vitamin E for all-day hydration and vibrant color.',
    price: 18.99,
    originalPrice: 34.99,
    categoryName: 'Beauty & Skincare',
    countInStock: 85,
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.7,
    numReviews: 432,
    soldCount: 7654,
    brand: 'GlamBeauty',
    tags: ['lipstick', 'matte', 'makeup', 'beauty'],
    colors: ['#FF0000', '#FF69B4', '#8B0000', '#FFC0CB', '#D2691E', '#800020'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_21',
    name: 'Hyaluronic Acid Serum',
    description: 'Advanced hydrating serum with 2% hyaluronic acid, vitamin B5, and ceramides. Deeply moisturizes, plumps fine lines, and restores skin barrier. Suitable for all skin types.',
    price: 22.99,
    originalPrice: 38.99,
    categoryName: 'Beauty & Skincare',
    countInStock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.9,
    numReviews: 567,
    soldCount: 9876,
    brand: 'SkinGlow',
    tags: ['serum', 'skincare', 'hyaluronic', 'beauty'],
    colors: [],
    sizes: ['30ml', '50ml'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_22',
    name: 'Rose Gold Makeup Brush Set',
    description: 'Professional 12-piece makeup brush set with ultra-soft synthetic bristles and rose gold metal handles. Includes brushes for face, eyes, and lips in a chic travel case.',
    price: 24.99,
    originalPrice: 42.99,
    categoryName: 'Beauty & Skincare',
    countInStock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.6,
    numReviews: 234,
    soldCount: 3456,
    brand: 'BrushLux',
    tags: ['brushes', 'makeup', 'rose-gold', 'beauty'],
    colors: ['#B76E79'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_23',
    name: 'Signature Eau de Parfum',
    description: 'Captivating unisex fragrance with top notes of bergamot and pink pepper, heart notes of jasmine and iris, and base notes of sandalwood and musk. 50ml bottle.',
    price: 42.99,
    originalPrice: 65.99,
    categoryName: 'Beauty & Skincare',
    countInStock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.8,
    numReviews: 189,
    soldCount: 2345,
    brand: 'AuraScent',
    tags: ['perfume', 'fragrance', 'unisex', 'beauty'],
    colors: [],
    sizes: ['30ml', '50ml', '100ml'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_24',
    name: 'Vitamin C Brightening Moisturizer',
    description: 'Lightweight daily moisturizer enriched with 15% vitamin C, niacinamide, and SPF 30. Brightens dull skin, evens tone, and protects against UV damage.',
    price: 19.99,
    originalPrice: 32.99,
    categoryName: 'Beauty & Skincare',
    countInStock: 95,
    imageUrl: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.5,
    numReviews: 345,
    soldCount: 5432,
    brand: 'SkinGlow',
    tags: ['moisturizer', 'vitamin-c', 'skincare', 'beauty'],
    colors: [],
    sizes: ['50ml'],
    createdAt: new Date(),
  },

  // ===== JEWELRY & WATCHES =====
  {
    _id: 'prod_25',
    name: 'Layered Gold Chain Necklace',
    description: 'Delicate triple-layered gold chain necklace with a star pendant, moon charm, and dainty bar. 18K gold-plated stainless steel, tarnish-resistant and hypoallergenic.',
    price: 14.99,
    originalPrice: 24.99,
    categoryName: 'Jewelry & Watches',
    countInStock: 110,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.7,
    numReviews: 389,
    soldCount: 6543,
    brand: 'GoldAura',
    tags: ['necklace', 'gold', 'layered', 'jewelry'],
    colors: ['#FFD700', '#C0C0C0', '#B76E79'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_26',
    name: 'Minimalist Analog Watch',
    description: 'Ultra-thin minimalist analog watch with a genuine leather strap, Japanese quartz movement, and sapphire crystal glass. Water-resistant to 30m.',
    price: 59.99,
    originalPrice: 89.99,
    categoryName: 'Jewelry & Watches',
    countInStock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.8,
    numReviews: 156,
    soldCount: 1876,
    brand: 'TimeKeeper',
    tags: ['watch', 'minimalist', 'analog', 'unisex'],
    colors: ['#000000', '#8B4513', '#D2B48C'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_27',
    name: 'Crystal Drop Earrings',
    description: 'Sparkling crystal drop earrings featuring Swarovski-inspired stones set in rhodium-plated silver. Elegant teardrop design perfect for formal events.',
    price: 12.99,
    originalPrice: 22.99,
    categoryName: 'Jewelry & Watches',
    countInStock: 130,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.5,
    numReviews: 267,
    soldCount: 4321,
    brand: 'CrystalGem',
    tags: ['earrings', 'crystal', 'drop', 'women'],
    colors: ['#C0C0C0', '#FFD700', '#B76E79'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_28',
    name: 'Stackable Gemstone Rings Set',
    description: 'Set of 5 dainty stackable rings with colorful gemstone accents. 14K gold-plated sterling silver, adjustable sizing, and hypoallergenic for sensitive skin.',
    price: 16.99,
    originalPrice: 28.99,
    categoryName: 'Jewelry & Watches',
    countInStock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.6,
    numReviews: 198,
    soldCount: 3456,
    brand: 'GoldAura',
    tags: ['rings', 'stackable', 'gemstone', 'women'],
    colors: ['#FFD700', '#C0C0C0'],
    sizes: ['5', '6', '7', '8', '9'],
    createdAt: new Date(),
  },

  // ===== ELECTRONICS =====
  {
    _id: 'prod_29',
    name: 'AeroPulse Wireless ANC Headphones',
    description: 'Immersive spatial audio with hybrid active noise cancellation, custom 40mm titanium drivers, and 45-hour battery life. Premium over-ear design with memory foam cushions.',
    price: 79.99,
    originalPrice: 129.99,
    categoryName: 'Electronics',
    countInStock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.8,
    numReviews: 542,
    soldCount: 4567,
    brand: 'AeroTech',
    tags: ['headphones', 'wireless', 'noise-cancelling', 'electronics'],
    colors: ['#000000', '#FFFFFF', '#2F4F4F'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_30',
    name: 'Smart Fitness Tracker Watch',
    description: 'Advanced fitness tracker with AMOLED display, heart rate & SpO2 monitoring, GPS, sleep tracking, and 7-day battery. 50+ workout modes and swim-proof design.',
    price: 49.99,
    originalPrice: 79.99,
    categoryName: 'Electronics',
    countInStock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.7,
    numReviews: 389,
    soldCount: 5678,
    brand: 'Zenith',
    tags: ['smartwatch', 'fitness', 'health', 'electronics'],
    colors: ['#000000', '#2F4F4F', '#B76E79'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_31',
    name: 'Portable Bluetooth Speaker',
    description: '360-degree immersive sound with deep bass radiators, IPX7 waterproof rating, and 20 hours of battery life. Compact design with built-in microphone for calls.',
    price: 29.99,
    originalPrice: 44.99,
    categoryName: 'Electronics',
    countInStock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: false,
    rating: 4.6,
    numReviews: 234,
    soldCount: 3456,
    brand: 'SonicSphere',
    tags: ['speaker', 'bluetooth', 'waterproof', 'electronics'],
    colors: ['#000000', '#FF4500', '#4682B4'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_32',
    name: 'Wireless Earbuds Pro',
    description: 'True wireless earbuds with active noise cancellation, transparency mode, and spatial audio. 6-hour battery with 24-hour charging case. IPX4 sweat-resistant.',
    price: 34.99,
    originalPrice: 54.99,
    categoryName: 'Electronics',
    countInStock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f55?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    rating: 4.5,
    numReviews: 456,
    soldCount: 7890,
    brand: 'AeroTech',
    tags: ['earbuds', 'wireless', 'anc', 'electronics'],
    colors: ['#FFFFFF', '#000000'],
    sizes: [],
    createdAt: new Date(),
  },

  // ===== HOME & LIVING =====
  {
    _id: 'prod_33',
    name: 'Scented Soy Candle Collection',
    description: 'Set of 3 hand-poured soy wax candles in amber glass jars. Scents include Vanilla & Sandalwood, Fresh Linen, and Rose Garden. 40-hour burn time each.',
    price: 24.99,
    originalPrice: 39.99,
    categoryName: 'Home & Living',
    countInStock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602028915047-37269d1a73f7?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: false,
    rating: 4.7,
    numReviews: 178,
    soldCount: 2345,
    brand: 'AuraHome',
    tags: ['candle', 'scented', 'soy', 'home'],
    colors: [],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_34',
    name: 'Velvet Throw Pillow Covers (Set of 2)',
    description: 'Luxurious velvet pillow covers with hidden zipper closure. Set of 2 in complementary tones. 18x18 inch size, machine washable and fade-resistant.',
    price: 16.99,
    originalPrice: 26.99,
    categoryName: 'Home & Living',
    countInStock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0c2989dae0c?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584100936595-c0c2989dae0c?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.5,
    numReviews: 234,
    soldCount: 4567,
    brand: 'CozyNest',
    tags: ['pillow', 'velvet', 'decor', 'home'],
    colors: ['#2F4F4F', '#FFB6C1', '#F5F5DC', '#808080'],
    sizes: ['18x18"', '20x20"'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_35',
    name: 'Macramé Wall Hanging',
    description: 'Handcrafted macramé wall hanging made from 100% natural cotton cord. Bohemian-inspired design adds texture and warmth to any room. 24" wide x 36" long.',
    price: 28.99,
    originalPrice: 42.99,
    categoryName: 'Home & Living',
    countInStock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.6,
    numReviews: 89,
    soldCount: 876,
    brand: 'BohoDecor',
    tags: ['macrame', 'wall-art', 'boho', 'home'],
    colors: ['#F5F5DC', '#D2B48C'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_36',
    name: 'Ceramic Planter Set',
    description: 'Modern geometric ceramic planter set with bamboo saucers. Set of 3 in graduated sizes with drainage holes. Perfect for succulents, herbs, and small plants.',
    price: 22.99,
    originalPrice: 34.99,
    categoryName: 'Home & Living',
    countInStock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.4,
    numReviews: 156,
    soldCount: 2345,
    brand: 'GreenSpace',
    tags: ['planter', 'ceramic', 'decor', 'home'],
    colors: ['#FFFFFF', '#2F4F4F', '#D2B48C'],
    sizes: ['Small', 'Medium', 'Large'],
    createdAt: new Date(),
  },

  // ===== SPORTS & FITNESS =====
  {
    _id: 'prod_37',
    name: 'Premium Yoga Mat - Non-Slip',
    description: 'Extra thick 6mm yoga mat with alignment lines, dual-layer non-slip surface, and eco-friendly TPE material. Includes carrying strap. 72" x 24" standard size.',
    price: 28.99,
    originalPrice: 44.99,
    categoryName: 'Sports & Fitness',
    countInStock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.7,
    numReviews: 345,
    soldCount: 5678,
    brand: 'FlexFit',
    tags: ['yoga', 'mat', 'fitness', 'sports'],
    colors: ['#800080', '#2F4F4F', '#FFB6C1', '#87CEEB'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_38',
    name: 'Insulated Sports Water Bottle',
    description: 'Double-wall vacuum insulated stainless steel water bottle. Keeps drinks cold 24hrs / hot 12hrs. 750ml capacity with leak-proof lid and carry handle.',
    price: 18.99,
    originalPrice: 28.99,
    categoryName: 'Sports & Fitness',
    countInStock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.5,
    numReviews: 456,
    soldCount: 8765,
    brand: 'HydroGo',
    tags: ['bottle', 'insulated', 'sports', 'fitness'],
    colors: ['#000000', '#FFFFFF', '#4682B4', '#FF4500', '#2E8B57'],
    sizes: ['500ml', '750ml', '1L'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_39',
    name: 'Resistance Bands Set (5-Pack)',
    description: 'Complete set of 5 resistance bands with different tension levels (10-50 lbs). Made from premium natural latex with anti-snap technology. Includes door anchor and bag.',
    price: 14.99,
    originalPrice: 24.99,
    categoryName: 'Sports & Fitness',
    countInStock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.6,
    numReviews: 567,
    soldCount: 9876,
    brand: 'PowerFlex',
    tags: ['bands', 'resistance', 'workout', 'fitness'],
    colors: [],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_40',
    name: 'Gym Duffle Bag - Waterproof',
    description: 'Spacious 35L gym duffle bag with separate shoe compartment, wet pocket, and adjustable shoulder strap. Waterproof nylon with reinforced stitching.',
    price: 32.99,
    originalPrice: 49.99,
    categoryName: 'Sports & Fitness',
    countInStock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.4,
    numReviews: 123,
    soldCount: 1543,
    brand: 'ActiveCarry',
    tags: ['bag', 'gym', 'duffle', 'sports'],
    colors: ['#000000', '#2F4F4F', '#808080'],
    sizes: [],
    createdAt: new Date(),
  },

  // ===== KIDS & BABY =====
  {
    _id: 'prod_41',
    name: 'Organic Cotton Baby Romper',
    description: 'Super soft organic cotton baby romper with snap buttons for easy diaper changes. Adorable animal print design. GOTS certified, gentle on sensitive skin.',
    price: 16.99,
    originalPrice: 24.99,
    categoryName: 'Kids & Baby',
    countInStock: 75,
    imageUrl: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: false,
    rating: 4.8,
    numReviews: 234,
    soldCount: 3456,
    brand: 'TinyTots',
    tags: ['romper', 'baby', 'organic', 'kids'],
    colors: ['#FFB6C1', '#87CEEB', '#F5F5DC', '#FFFFFF'],
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_42',
    name: 'Kids Dinosaur Rain Boots',
    description: 'Colorful dinosaur-themed rain boots with slip-resistant soles, easy-pull handles, and waterproof rubber construction. Fun and functional for rainy adventures!',
    price: 19.99,
    originalPrice: 29.99,
    categoryName: 'Kids & Baby',
    countInStock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.7,
    numReviews: 167,
    soldCount: 2345,
    brand: 'KidStyle',
    tags: ['boots', 'rain', 'dinosaur', 'kids'],
    colors: ['#2E8B57', '#4682B4', '#FFD700'],
    sizes: ['5', '6', '7', '8', '9', '10', '11'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_43',
    name: 'Plush Stuffed Animal - Teddy Bear',
    description: 'Cuddly plush teddy bear made from ultra-soft, hypoallergenic microfiber. 14 inches tall with embroidered features and a satin bow tie. Perfect gift for kids of all ages.',
    price: 14.99,
    originalPrice: 22.99,
    categoryName: 'Kids & Baby',
    countInStock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1559715541-5daf8a0296d0?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1559715541-5daf8a0296d0?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    rating: 4.9,
    numReviews: 321,
    soldCount: 5432,
    brand: 'CuddlePals',
    tags: ['toy', 'plush', 'teddy', 'kids'],
    colors: ['#D2B48C', '#FFB6C1', '#808080'],
    sizes: ['Small (10")', 'Medium (14")', 'Large (18")'],
    createdAt: new Date(),
  },

  // ===== EXTRA TRENDING & FEATURED PRODUCTS =====
  {
    _id: 'prod_44',
    name: 'Linen Blend Summer Dress',
    description: 'Effortless linen-blend summer dress with a relaxed A-line silhouette, adjustable spaghetti straps, and a midi length. Breathable fabric for hot summer days.',
    price: 31.99,
    originalPrice: 49.99,
    categoryName: "Women's Fashion",
    countInStock: 38,
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.6,
    numReviews: 145,
    soldCount: 1987,
    brand: 'BreezeCo',
    tags: ['dress', 'linen', 'summer', 'women'],
    colors: ['#F5F5DC', '#FFFFFF', '#87CEEB'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_45',
    name: 'Leather Crossbody Mini Bag',
    description: 'Compact leather crossbody bag with adjustable strap, zip-top closure, and card slots inside. Perfect size for your phone, keys, and essentials on the go.',
    price: 26.99,
    originalPrice: 42.99,
    categoryName: 'Bags & Accessories',
    countInStock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    rating: 4.7,
    numReviews: 234,
    soldCount: 3210,
    brand: 'LeatherCraft',
    tags: ['bag', 'crossbody', 'leather', 'women'],
    colors: ['#8B4513', '#000000', '#D2B48C', '#800020'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_46',
    name: 'Smart LED Desk Lamp',
    description: 'Stepless dimming LED desk lamp with wireless charging pad base, touch controls, color temperature adjustment, and a 1-hour sleep timer. USB-C powered.',
    price: 34.99,
    originalPrice: 54.99,
    categoryName: 'Home & Living',
    countInStock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: false,
    isTrending: false,
    rating: 4.5,
    numReviews: 178,
    soldCount: 2567,
    brand: 'Luminary',
    tags: ['lamp', 'led', 'desk', 'home'],
    colors: ['#FFFFFF', '#000000'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_47',
    name: 'Knit Beanie Hat',
    description: 'Soft chunky knit beanie hat with a fold-over cuff design. Made from acrylic-wool blend for warmth and comfort. One size fits most.',
    price: 9.99,
    originalPrice: 16.99,
    categoryName: 'Bags & Accessories',
    countInStock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    rating: 4.3,
    numReviews: 345,
    soldCount: 6789,
    brand: 'CozyKnit',
    tags: ['beanie', 'hat', 'winter', 'accessories'],
    colors: ['#000000', '#808080', '#F5F5DC', '#8B4513', '#800020'],
    sizes: [],
    createdAt: new Date(),
  },
  {
    _id: 'prod_48',
    name: 'Running Performance Sneakers',
    description: 'Lightweight running shoes with responsive foam midsole, breathable engineered mesh upper, and carbon rubber outsole. Designed for both road and track performance.',
    price: 62.99,
    originalPrice: 89.99,
    categoryName: 'Shoes & Sneakers',
    countInStock: 32,
    imageUrl: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80'],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.8,
    numReviews: 289,
    soldCount: 4321,
    brand: 'SpeedRun',
    tags: ['sneakers', 'running', 'performance', 'sports'],
    colors: ['#000000', '#FF4500', '#FFFFFF', '#4682B4'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_49',
    name: 'Cozy Fleece Blanket',
    description: 'Ultra-soft microfiber fleece blanket with double-sided design. Lightweight yet incredibly warm. Machine washable and wrinkle-resistant. 60" x 80" throw size.',
    price: 21.99,
    originalPrice: 34.99,
    categoryName: 'Home & Living',
    countInStock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    rating: 4.6,
    numReviews: 234,
    soldCount: 3456,
    brand: 'CozyNest',
    tags: ['blanket', 'fleece', 'cozy', 'home'],
    colors: ['#808080', '#F5F5DC', '#2F4F4F', '#FFB6C1'],
    sizes: ['Throw (50x60")', 'Full (60x80")', 'Queen (90x90")'],
    createdAt: new Date(),
  },
  {
    _id: 'prod_50',
    name: 'Pearl Charm Bracelet',
    description: 'Dainty freshwater pearl charm bracelet with adjustable gold-plated chain. Features a heart lock clasp and toggle closure. Comes in a velvet gift box.',
    price: 18.99,
    originalPrice: 29.99,
    categoryName: 'Jewelry & Watches',
    countInStock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80'],
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    rating: 4.7,
    numReviews: 198,
    soldCount: 2876,
    brand: 'PearlLux',
    tags: ['bracelet', 'pearl', 'charm', 'jewelry'],
    colors: ['#FFD700', '#C0C0C0'],
    sizes: [],
    createdAt: new Date(),
  },
];

const hashedAdminPassword = bcrypt.hashSync('admin123', 10);
const hashedUserPassword = bcrypt.hashSync('user123', 10);

const initialUsers = [
  {
    _id: 'usr_admin',
    name: 'System Admin',
    email: 'admin@nexcart.com',
    password: hashedAdminPassword,
    role: 'admin',
    phone: '+1 (555) 019-2831',
    address: { street: '100 NexCart HQ Ave', city: 'Techopolis', state: 'CA', postalCode: '94016', country: 'United States' },
    createdAt: new Date(),
  },
  {
    _id: 'usr_customer',
    name: 'John Doe',
    email: 'john@example.com',
    password: hashedUserPassword,
    role: 'customer',
    phone: '+1 (555) 392-1049',
    address: { street: '452 Innovation Blvd', city: 'San Francisco', state: 'CA', postalCode: '94107', country: 'United States' },
    createdAt: new Date(),
  },
];

const initialOrders = [
  {
    _id: 'ord_1001',
    user: { _id: 'usr_customer', name: 'John Doe', email: 'john@example.com' },
    orderItems: [
      { name: 'Floral Wrap Midi Dress', quantity: 1, price: 34.99, imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80', product: 'prod_1' },
      { name: 'Layered Gold Chain Necklace', quantity: 2, price: 14.99, imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80', product: 'prod_25' },
    ],
    shippingAddress: { fullName: 'John Doe', address: '452 Innovation Blvd', city: 'San Francisco', postalCode: '94107', country: 'United States', phone: '+1 (555) 392-1049' },
    paymentMethod: 'Simulated Card Payment',
    itemsPrice: 64.97,
    taxPrice: 5.20,
    shippingPrice: 0,
    totalPrice: 70.17,
    isPaid: true,
    paidAt: new Date(),
    isDelivered: false,
    status: 'Processing',
    createdAt: new Date(),
  },
];

class InMemoryStore {
  constructor() {
    this.categories = [...initialCategories];
    this.products = [...initialProducts];
    this.users = [...initialUsers];
    this.orders = [...initialOrders];
    this.carts = {};
  }
}

const store = new InMemoryStore();
module.exports = store;
